version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: library_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
#    env_file:
#      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - library_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: Library.WebApi/Dockerfile
    container_name: library_webapi
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "5000:8080"
    networks:
      - library_network

volumes:
  postgres_data:
  
  

networks:
  library_network:
    driver: bridge

